[package]
name = "serv"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
mms-api.workspace = true
mms-db.workspace = true

axum.workspace = true
axum-extra.workspace = true
tokio.workspace = true
tower_governor.workspace = true
tower-http.workspace = true
tracing.workspace = true
