[package]
name = "serv"
version.workspace = true
edition.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mms-api.workspace = true
