[package]
name = "shuttle-serv"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
mms-api = { workspace = true, features = ["shuttle"] }
mms-db.workspace = true

anyhow.workspace = true
axum.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower_governor.workspace = true
tower-http.workspace = true
tracing.workspace = true

# Deployment dependencies (Shuttle.rs)
shuttle-runtime.workspace = true
shuttle-axum.workspace = true
shuttle-shared-db.workspace = true
